### ISSUE TITLE
Whitespace errors

### ISSUE THREAD

**Issue by ghost** [codergirlstl/parent-site#2]
Hey! Nice job so far!

Not a big deal, but I noticed your indentation is wrong in caledar_controller.rb and todo_items_parent_site_controller.rb

It won't affect the code function, but it will cause problems when humans try to read the code and make you look bad if you use this as an example for a job interview.

Always two space indentation for ruby!

Overall, looking good so far. Didn't run the code but did a quick look through most of the files.

**Comment by codergirlstl** [comment]
Thanks!
